name: falmodel
description: A new Flutter package project.
version: 1.0.1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  faltool:
    git:
      url: https://github.com/THE-EXISTING/faltool.git
      ref: develop

  #PLATFORM: All
  equatable: ^2.0.5
  dio: ^5.4.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
