name: falmodel
description: A new Flutter package project.
version: 1.2.5

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  faltool:
    git:
      url: https://github.com/THE-EXISTING/faltool.git
      ref: 1.0.11

  #PLATFORM: All
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
